<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "cuenta".
 *
 * @property integer $id
 * @property string $cbu
 * @property integer $personaid
 * @property integer $bancoid
 * @property integer $tipo_cuentaid
 * @property integer $sub_sucursalid
 * @property string $create_at
 *
 * @property \app\models\Banco $banco
 * @property \app\models\SubSucursal $subSucursal
 * @property \app\models\TipoCuenta $tipoCuenta
 * @property string $aliasModel
 */
abstract class Cuenta extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'cuenta';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['cbu', 'personaid', 'bancoid', 'tipo_cuentaid'], 'required'],
            [['personaid', 'bancoid', 'tipo_cuentaid', 'sub_sucursalid'], 'integer'],
            [['create_at'], 'safe'],
            [['cbu'], 'string', 'max' => 45],
            [['cbu'], 'unique'],
            [['bancoid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Banco::className(), 'targetAttribute' => ['bancoid' => 'id']],
            [['sub_sucursalid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\SubSucursal::className(), 'targetAttribute' => ['sub_sucursalid' => 'id']],
            [['tipo_cuentaid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\TipoCuenta::className(), 'targetAttribute' => ['tipo_cuentaid' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'cbu' => 'Cbu',
            'personaid' => 'Personaid',
            'bancoid' => 'Bancoid',
            'tipo_cuentaid' => 'Tipo Cuentaid',
            'sub_sucursalid' => 'Sub Sucursalid',
            'create_at' => 'Create At',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'sub_sucursalid' => ' Nos indica de donde fue dado de alta
',
            'create_at' => ' Nos indica de donde fue dado de alta
',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBanco()
    {
        return $this->hasOne(\app\models\Banco::className(), ['id' => 'bancoid']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSubSucursal()
    {
        return $this->hasOne(\app\models\SubSucursal::className(), ['id' => 'sub_sucursalid']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTipoCuenta()
    {
        return $this->hasOne(\app\models\TipoCuenta::className(), ['id' => 'tipo_cuentaid']);
    }




}
