<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "cuenta".
 *
 * @property integer $id
 * @property string $cbu
 * @property string $personaid
 * @property integer $bancoid
 * @property integer $tipo_cuentaid
 *
 * @property \app\models\Banco $banco
 * @property \app\models\TipoCuenta $tipoCuenta
 * @property string $aliasModel
 */
abstract class Cuenta extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'cuenta';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id', 'cbu', 'bancoid', 'tipo_cuentaid'], 'required'],
            [['id', 'bancoid', 'tipo_cuentaid'], 'integer'],
            [['cbu', 'personaid'], 'string', 'max' => 45],
            [['cbu'], 'unique'],
            [['id'], 'unique'],
            [['bancoid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Banco::className(), 'targetAttribute' => ['bancoid' => 'id']],
            [['tipo_cuentaid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\TipoCuenta::className(), 'targetAttribute' => ['tipo_cuentaid' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'cbu' => 'Cbu',
            'personaid' => 'Personaid',
            'bancoid' => 'Bancoid',
            'tipo_cuentaid' => 'Tipo Cuentaid',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBanco()
    {
        return $this->hasOne(\app\models\Banco::className(), ['id' => 'bancoid']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTipoCuenta()
    {
        return $this->hasOne(\app\models\TipoCuenta::className(), ['id' => 'tipo_cuentaid']);
    }




}
