<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "prestacion".
 *
 * @property integer $id
 * @property double $monto
 * @property string $create_at
 * @property integer $personaid
 * @property string $proposito
 * @property string $observacion
 * @property string $aliasModel
 */
abstract class Prestacion extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'prestacion';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['monto', 'create_at', 'personaid'], 'required'],
            [['monto'], 'number'],
            [['create_at'], 'safe'],
            [['personaid'], 'integer'],
            [['proposito', 'observacion'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'monto' => 'Monto',
            'create_at' => 'Create At',
            'personaid' => 'Personaid',
            'proposito' => 'Proposito',
            'observacion' => 'Observacion',
        ];
    }




}
