<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "sub_sucursal".
 *
 * @property integer $id
 * @property string $localidad
 * @property string $codigo_postal
 * @property string $codigo
 * @property integer $sucursalid
 *
 * @property \app\models\Cuenta[] $cuentas
 * @property \app\models\Sucursal $sucursal
 * @property string $aliasModel
 */
abstract class SubSucursal extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'sub_sucursal';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['sucursalid'], 'required'],
            [['sucursalid'], 'integer'],
            [['localidad', 'codigo_postal', 'codigo'], 'string', 'max' => 45],
            [['sucursalid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Sucursal::className(), 'targetAttribute' => ['sucursalid' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'localidad' => 'Localidad',
            'codigo_postal' => 'Codigo Postal',
            'codigo' => 'Codigo',
            'sucursalid' => 'Sucursalid',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCuentas()
    {
        return $this->hasMany(\app\models\Cuenta::className(), ['sub_sucursalid' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSucursal()
    {
        return $this->hasOne(\app\models\Sucursal::className(), ['id' => 'sucursalid']);
    }




}
