<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "sucursal".
 *
 * @property integer $id
 * @property string $nombre
 * @property string $codigo
 *
 * @property \app\models\SubSucursal[] $subSucursals
 * @property string $aliasModel
 */
abstract class Sucursal extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'sucursal';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nombre', 'codigo'], 'string', 'max' => 45]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nombre' => 'Nombre',
            'codigo' => 'Codigo',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSubSucursals()
    {
        return $this->hasMany(\app\models\SubSucursal::className(), ['sucursalid' => 'id']);
    }




}
